resources:
  - url: http://127.0.0.1:5000/air-purifier-card.js
    type: module
views:
  - cards:
      - type: custom:air-purifier-card
        name: Air purifier Card
        entity: sun.sun
        test_gui: true
